name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-tools-dev qt6-base-dev
          qtchooser -install qt6 $(which qmake6)

      - name: Get build timestamp
        id: id_date
        run: echo "timestamp=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_OUTPUT

      - name: Get app version
        id: id_version
        run: |
          cd Software/RF2DFieldSolver
          fw_major=`grep -oP '(?<=FW_MAJOR=)[0-9]+' RF2DFieldSolver.pro`
          fw_minor=`grep -oP '(?<=FW_MINOR=)[0-9]+' RF2DFieldSolver.pro`
          fw_patch=`grep -oP '(?<=FW_PATCH=)[0-9]+' RF2DFieldSolver.pro` 
          echo "app_version=v$fw_major.$fw_minor.$fw_patch-${{steps.id_date.outputs.timestamp}}" >> $GITHUB_OUTPUT

      - name: Build application
        run: |
          cd Software/RF2DFieldSolver
          export QT_SELECT=qt6
          qmake RF2DFieldSolver.pro
          make -j9
        shell: bash

      - name: Upload artifact
        env: 
          FIELDSOLVER_VERSION: "${{steps.id_version.outputs.app_version}}"
        uses: actions/upload-artifact@v4
        with:
          name: RF2DFieldSolver-Ubuntu-${{env.FIELDSOLVER_VERSION}}
          path: Software/RF2DFieldSolver/RF2DFieldSolver
          
  Windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.0'
          arch: 'win64_mingw81'
      
      - name: Get build timestamp
        shell: msys2 {0}
        id: id_date
        run: echo "timestamp=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_OUTPUT

      - name: Get app version
        id: id_version
        shell: msys2 {0}
        run: |
          cd Software/RF2DFieldSolver
          fw_major=`grep -oP '(?<=FW_MAJOR=)[0-9]+' RF2DFieldSolver.pro`
          fw_minor=`grep -oP '(?<=FW_MINOR=)[0-9]+' RF2DFieldSolver.pro`
          fw_patch=`grep -oP '(?<=FW_PATCH=)[0-9]+' RF2DFieldSolver.pro` 
          echo "app_version=v$fw_major.$fw_minor.$fw_patch-${{steps.id_date.outputs.timestamp}}" >> $GITHUB_OUTPUT

      - name: Build application
        run: |
          cd Software/RF2DFieldSolver
          qmake RF2DFieldSolver.pro
          make -j9
        shell: cmd

      - name: Deploy application
        run: |
          cd Software/RF2DFieldSolver/release
          del *.o *.cpp
          windeployqt.exe .
          copy ..\..\..\..\Qt\6.2.0\mingw81_64\bin\libwinpthread-1.dll .
          copy ..\..\..\..\Qt\6.2.0\mingw81_64\bin\libgcc_s_seh-1.dll .
          copy "..\..\..\..\Qt\6.2.0\mingw81_64\bin\libstdc++-6.dll" .
          copy ..\..\..\..\Qt\6.2.0\mingw81_64\bin\Qt6OpenGL.dll .
        shell: cmd
        
      - name: Upload
        uses: actions/upload-artifact@v4
        env: 
          FIELDSOLVER_VERSION: "${{steps.id_version.outputs.app_version}}"
        with:
          name: RF2DFieldSolver_Windows-${{env.FIELDSOLVER_VERSION}}
          path: Software/RF2DFieldSolver/release
